/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import gerenciadordepatrimonio.Servidor;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Vitor Hugo
 */
public class TelaServidor extends javax.swing.JFrame {
    TelaLogin l = null;
    /**
     * Creates new form TelaAdm
     */
    public TelaServidor(Servidor s) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Gerenciador de Patrimônio");
    }
    
    public TelaServidor(){
        initComponents();
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemViewServs = new javax.swing.JMenuItem();
        jMenuItemViewCampus = new javax.swing.JMenuItem();
        jMenuItemViewAmbientes = new javax.swing.JMenuItem();
        jMenuItemViewItens = new javax.swing.JMenuItem();
        jMenuItemViewMovAmb = new javax.swing.JMenuItem();
        jMenuItemViewMovDonos = new javax.swing.JMenuItem();
        jMenuItemViewRev = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1465, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jMenu2.setText("Visualizar");

        jMenuItemViewServs.setText("Servidores");
        jMenuItemViewServs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewServsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewServs);

        jMenuItemViewCampus.setText("Campus");
        jMenuItemViewCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewCampusActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewCampus);

        jMenuItemViewAmbientes.setText("Ambientes");
        jMenuItemViewAmbientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewAmbientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewAmbientes);

        jMenuItemViewItens.setText("Itens");
        jMenuItemViewItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewItensActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewItens);

        jMenuItemViewMovAmb.setText("Movimentações entre ambientes");
        jMenuItemViewMovAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewMovAmbActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewMovAmb);

        jMenuItemViewMovDonos.setText("Movimentações entre donos");
        jMenuItemViewMovDonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewMovDonosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewMovDonos);

        jMenuItemViewRev.setText("Revisões");
        jMenuItemViewRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewRevActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewRev);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        jMenuItem15.setText("Ambientes");
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("Servidores");
        jMenu3.add(jMenuItem16);

        jMenuBar1.add(jMenu3);

        jMenuLogout.setText("Trocar usuário");
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        l = new TelaLogin();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuItemViewServsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewServsActionPerformed
        // TODO add your handling code here:
        ViewServidores frameInterno = new ViewServidores();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewServsActionPerformed

    private void jMenuItemViewCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCampusActionPerformed
        // TODO add your handling code here:
        ViewCampus frameInterno = new ViewCampus();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewCampusActionPerformed

    private void jMenuItemViewAmbientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewAmbientesActionPerformed
        // TODO add your handling code here:
        ViewAmbientes frameInterno = new ViewAmbientes();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewAmbientesActionPerformed

    private void jMenuItemViewItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewItensActionPerformed
        // TODO add your handling code here:
        ViewItens frameInterno = new ViewItens();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewItensActionPerformed

    private void jMenuItemViewMovAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewMovAmbActionPerformed
        // TODO add your handling code here:
        ViewMovAmb frameInterno = new ViewMovAmb();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewMovAmbActionPerformed

    private void jMenuItemViewMovDonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewMovDonosActionPerformed
        // TODO add your handling code here:
        ViewMovDono frameInterno = new ViewMovDono();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewMovDonosActionPerformed

    private void jMenuItemViewRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewRevActionPerformed
        // TODO add your handling code here:
        ViewRevisoes frameInterno = new ViewRevisoes();
        frameInterno.setVisible(true);
        jDesktopPane1.add(frameInterno);
        centralizaForm(frameInterno);
    }//GEN-LAST:event_jMenuItemViewRevActionPerformed

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        frame.toFront();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItemViewAmbientes;
    private javax.swing.JMenuItem jMenuItemViewCampus;
    private javax.swing.JMenuItem jMenuItemViewItens;
    private javax.swing.JMenuItem jMenuItemViewMovAmb;
    private javax.swing.JMenuItem jMenuItemViewMovDonos;
    private javax.swing.JMenuItem jMenuItemViewRev;
    private javax.swing.JMenuItem jMenuItemViewServs;
    private javax.swing.JMenu jMenuLogout;
    // End of variables declaration//GEN-END:variables
}
